output = "out_files_test/512x512_2spp/ref_path-tracer/10_uniform.json"
uid = "outputs_test/512x512_2spp/ref_path-tracer/uniform/p10"

[tools]
path = "../"
tracer = "/home/ggc/ray_tracing/RayTracingInVulkan/"
gpgpusim = "/home/ggc/ray_tracing/gpgpu-sim_emerald/"
embree_vars = "/opt/embree-3.12.2.x86_64.linux/embree-vars.sh"
nvidia_vk_icd_filenames = "/etc/vulkan/icd.d/nvidia_icd.json"
lavapipe_vk_icd_filenames = "/home/ggc/ray_tracing/mesa/lib/share/vulkan/icd.d/lvp_icd.x86_64.json"

[workload]
width = 512
height = 512
samples = 2
scene_name = "ref"
scene_number = 30
shader_type = "path-tracer"
shadow_rays = 2

[heatmap]
path = "/home/ggc/ray_tracing/Predictor/heatmaps/512x512_2spp/path-tracer/30.ppm"
scale = 1.0
clusters = 5
max_iter = 500
epsilon = 0.05

[model]
gpuconfig = "gpgpusim.config"
downscale_factor = 1
section_width = 32
section_height = 2
iterations = 1
enable_edges = true
all_pixels_in_chunks = false
const_percentage = 0.10
distribution = "uniform"
num_pixels_scale = 0.5
min_trace_perc = 0.05
shared_parameters = ["gpgpu_n_clusters", "gpgpu_n_mem"]
chunks_type = "coarse-grained"
debug = true
metrics_to_collect = [
	'gpu_ipc',
	'gpu_sim_cycle',
	'rt_avg_nodes_per_ray',
	'L1D_total_cache_miss_rate',
	'L2_total_cache_miss_rate',
	'rt_avg_warp_occupancy',
	'rt_avg_efficiency',
	'rt_avg_performance',
	'rt_avg_op_intensity',
	'rt_avg_warp_latency',
	'rt_avg_thread_latency',
	'rt_l2_overall_miss_rate',
	'rt_l1_overall_miss_rate',
	'dram_eff',
	'bwutil',
	'running_time'
]
