output = <<output>>
uid = <<uid>>

[tools]
path = "../"
tracer = "/home/ggc/ray_tracing/RayTracingInVulkan/"
gpgpusim = "/home/ggc/ray_tracing/gpgpu-sim_emerald/"
embree_vars = "/opt/embree-3.12.2.x86_64.linux/embree-vars.sh"
nvidia_vk_icd_filenames = "/etc/vulkan/icd.d/nvidia_icd.json"
lavapipe_vk_icd_filenames = "/home/ggc/ray_tracing/mesa/lib/share/vulkan/icd.d/lvp_icd.x86_64.json"

[workload]
width = 512
height = 512
samples = 2
scene_name = <<scene_name>>
scene_number = <<scene_number>>
shader_type = <<shader_type>>
shadow_rays = <<shadow_rays>>

[heatmap]
path = <<heatmap_path>>
scale = 1.0
clusters = 5
max_iter = 500
epsilon = 0.05

[model]
gpuconfig = "gpgpusim.config"
downscale = false
section_width = 32
section_height = 2
iterations = 1
enable_edges = true
all_pixels_in_chunks = <<all_pixels>>
const_percentage = <<const_perc>>
distribution = <<dist>>
num_pixels_scale = 0.5
min_trace_perc = 0.05
shared_parameters = ["gpgpu_n_clusters", "gpgpu_n_mem"]
chunks_type = "coarse-grained"
debug = true
metrics_to_collect = [
	'gpu_ipc',
	'rt_avg_nodes_per_ray',
	'L1D_total_cache_miss_rate',
	'L2_total_cache_miss_rate',
	'rt_avg_warp_occupancy',
	'rt_avg_efficiency',
	'rt_avg_performance',
	'rt_avg_op_intensity',
	'rt_avg_warp_latency',
	'rt_avg_thread_latency',
	'rt_l2_overall_miss_rate',
	'rt_l1_overall_miss_rate',
	'dram_eff',
	'bwutil',
	'running_time'
]
